#
# PvP Game Manager Sample Configuration
#
# This file describes some high-level configuration about the server as a
# whole.  Map-specific configuration should be specified in the map folder.

map:
  sources:
    - default
    - maps/

map-pools:
  enabled: true
  path: map-pools.yml

restart:
  enabled: true
  uptime: 3h
  match-limit: 15

start:
  auto: true                  # Start the match automatically when ready
  countdown: 30s              # Default match start countdown
  huddle: 0s                  # Team huddle duration

cycle:
  countdown: 30s              # Default countdown for cycle commands
  running-match: false        # Allow cycle commands during a running match without the -f flag
  match-empty:                # Cycle if a running match empties out
    enabled: false
    countdown: 5s
  match-end:                  # Cycle when a match ends
    enabled: true
    countdown: 30s

join:
  priority-kick: true         # Kick non-privileged players to make room for privileged ones
  mid-match: true             # Allow players to join after the match has started (does not override Blitz rule)
  commit-players: false       # Do various things to keep players in the match once committed
  capacity:
    enabled: true
    overfill: true            # Enable overfill (false disables overfill, regardless of XML)
    overfill-ratio: 1.25      # Default value, XML overrides this

minimum-players: 1

teams:
  minimum-players: 0
  allow-choose: true       # Allow privileged players to choose their team
  allow-switch: true       # Allow players to be on multiple teams in the same match
  try-balance: false       # Try to balance teams if they are stacked
  require-even: false      # Force evenly sized teams when using queued joins

broadcast:
  enabled: true
  frequency: 600

arrow-removal:
  enabled: true
  delay: 10

fishing:
  disable-treasure: true

scoreboard:
  show-proximity: false
  precise-progress: false

wool:
  auto-refill: true

player-list:
  enabled: true

motd:
  enabled: true                                          # If the custom PGM motd should be shown to players
  ## Available Placeholders ##
  # {map.name} - Name of the currently playing map
  # {map.version} - Version of the currently playing map
  # {state.color} - Chat color (with the §) describing the current match's state (configured below)
  # {state.name} - Name of the current match state, with an uppercase first letter
  # {state.name-lower} - Fully lowercase name of the current match state
  format: "{state.color}» &b{map.name} {state.color}«"   # Format of the MOTD
  colors:
    idle: gray                                           # Color designating a match which is waiting to start
    starting: yellow                                     # Color designating a match which is starting
    running: green                                       # Color designating a match which is currently running
    finished: red                                        # Color designating a match which has ended

groups:
  admin:
    op: true
    priority: 10
    prefix:
      symbol: ❖
      color: gold

experiments:
  match-preload-seconds: 10 # Number of seconds to pre-load a match and its world before cycle
  match-destroy-seconds: 10 # Number of seconds to wait before unloading a world after the match has unloaded
  match-teleports-per-second: 10 # Number of players to teleport per second to a new match on cycle
  tab-render-ticks: 10 # Number of ticks before invalidating the tab list

sidebar:
  # Messages may be formatted with '&'
  # Leave blank to disable
  top: ""
  bottom: ""
  # If the sidebar message should overwrite lines in the sidebar when it is full
  overwrite: false
